### ISSUE TITLE
Access the pure RGB of THUE-ACT-50 CHL

### ISSUE THREAD

**Issue by MrFisher97** [lujiaxuan0520/THU-EACT-50#5]
Hi,

I am really interesed in your research on Event camera. In particular, I noticed that you utilized the pure RGB data from the THUE-ACT-50 CHL dataset as input in Section V.C.3 of your work. However, I have been unable to locate the RGB resource for the THUE-ACT-50 CHL in the provided GitHub repository.

I would greatly appreciate it if you could provide access to the RGB video or direct me to the appropriate location where I can find it.

Thank you for your time and consideration.

Best regards,
fisher.

**Comment by QiWang233** [comment]
已收到邮件。

**Comment by lujiaxuan0520** [comment]
Dear @wanzengy 

Thank you for your interest in our event camera datasets.  Regarding your inquiry about the availability of RGB frames, for the THUE-ACT-50 dataset, we would like to clarify that the dataset was collected using a CeleX-V event camera, which does not capture RGB frames. Consequently, we do not have corresponding RGB data for this dataset. However, for the THUE-ACT-50-CHL dataset, which was acquired with a DAVIS346 camera, there are indeed RGB image frames included. It is important to note that these RGB frames were captured in challenging scenarios, which means the quality of the frames might not meet high standards due to the complexity of the scenes and the limitations of the capturing device in those conditions.

If these RGB frames are still of interest to you despite the potential quality concerns, we have made them available on Baidu Cloud. Please ensure that you comply with the privacy and policy regulations by not disclosing or exposing the dataset to unauthorized personnel as it does contain sensitive information that could lead to privacy breaches.

Here is the Baidu Cloud link to access the dataset with RGB frames: pan.baidu.com/s/1gfwwBffGIfS4oN_HgUE4rg with code girt

Best regards,
Jiaxuan

**Comment by MrFisher97** [comment]
Really apperatcaite your shareing and it would be truly beneficial to get the video. And I promise that I would comply with the privacy and policy regulation. Thanks again for your sharing.
